import type { Metadata } from "next";
import localFont from "next/font/local"
import Navbar from "../component/ui/navbar";
import Footer from "@/component/ui/footer";
import NextTopLoader from "nextjs-toploader";
import { ReactLenis } from "lenis/react";
import "./globals.css";
import 'lenis/dist/lenis.css'
import "./globals.css";
import Message from "@/component/ui/message";

const authorBold = localFont({
  src: "font/Author-Bold.otf",
  variable: "--author-bold",
});

const authorRegular = localFont({
  src: "font/Author-Regular.otf",
  variable: "--author-regular",
});

const satoshiRegular = localFont({
  src: "font/Satoshi-Regular.otf",
  variable: "--satoshi-regular",
});

export const metadata: Metadata = {
  title: "Oasis Homes",
  description: "Generated by create next app",
};

// export const revalidate = 604800; // 7 days

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${authorBold.variable} ${authorRegular.variable} ${satoshiRegular.variable}`}>
          <NextTopLoader color="#FFB22C" showSpinner={false} />
          <Navbar />
          {children}
          <Footer />
          <Message />
        </body>
      </ReactLenis>
    </html>
  );
}
